stages:
  - build

job1:
  tags:
    - docker
  stage: build
  script:
    - docker login -u taisun -p $DOCKERPASS
    - docker build -f Dockerfile -t taisun/webapp:$CI_BUILD_REF
    - docker build -f Dockerfile.dev -t taisun/webapp:$CI_BUILD_REF.dev
    - docker tag taisun/webapp:$CI_BUILD_REF taisun/webapp:latest
    - docker tag taisun/webapp:$CI_BUILD_REF.dev taisun/webapp:latest.dev
    - docker push taisun/webapp:$CI_BUILD_REF
    - docker push taisun/webapp:$CI_BUILD_REF.dev
    - docker push taisun/webapp:latest
    - docker push taisun/webapp:latest.dev
