sudo: true

language: bash

services:
  - docker

env:
  global:
    - DEBIAN_FRONTEND="noninteractive"
    - BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S%:z')
    - DOCKERHUB_LIVE="taisun/webapp"
    - GITHUB_REPO="Taisun-Docker/taisun"

jobs:
  include:
    - stage: BuildCommitDev
      if: (NOT (type IN (pull_request))) AND (tag IS blank)
      before_install:
        - /bin/bash pre_install
      script:
        # Build Dev image
        - docker build --no-cache -f Dockerfile.dev --build-arg BUILD_DATE="${BUILD_DATE}" -t ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT}.dev .
        - docker tag ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT}.dev ${DOCKERHUB_LIVE}:latest.dev
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_LIVE}:${TRAVIS_COMMIT}.dev
        - docker push ${DOCKERHUB_LIVE}:latest.dev
