#Dockerfile for Taisun base development image
#2017
#Use the node base image
FROM node:8.4

MAINTAINER Ryan Kuba <ryankuba@gmail.com>

# Grab Cloud9 and install under root
RUN curl https://s3-us-west-2.amazonaws.com/taisun-pubfiles/cloud9.tar.gz | tar xz -C /

#Install Dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git supervisor software-properties-common apt-transport-https && \
  curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* &&\
  curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose &&\
  chmod +x /usr/local/bin/docker-compose

# Install Nodemon
RUN npm install -g nodemon

# Install git wrapper
RUN mv /usr/bin/git /usr/bin/gitbin
COPY ./git /usr/bin/git

#Copy over supervisor config file
COPY ./taisun.conf.dev /etc/supervisor/conf.d/taisun.conf

# Copy over application and install dependencies
RUN mkdir -p /usr/src/Taisun
COPY . /usr/src/Taisun
WORKDIR /usr/src/Taisun
RUN npm install

#Copy over git tree
COPY ./.git /usr/src/Taisun/.git

# Set the Origin to the https endpoint for easy pushes and pulls
RUN cd /usr/src/Taisun && git remote set-url origin https://gitlab.com/thelamer/taisun.git

#App runs on port 80 dev interface runs on port 8000

EXPOSE 80
EXPOSE 8000

#Run Supervisor
CMD ["/usr/bin/supervisord"]
