version: '3.7'

services:
  taisun:
    image: linuxserver/taisun
    container_name: taisun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    network_mode: bridge
    restart: unless-stopped

